/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ApplicationConfig {
  GET_SCRAPBOX_PAGES_ENDPOINT: string;
  SCRAPBOX_COOKIE: string;
  SLACK_INCOMING_WEBHOOK: string;
  [k: string]: unknown;
}
