// Generated by https://quicktype.io

export interface ScrapboxPagesApiResponse {
  projectName: string;
  skip: number;
  limit: number;
  count: number;
  pages: Page[];
}

export interface Page {
  id: string;
  title: string;
  image: null;
  descriptions: string[];
  user: User;
  pin: number;
  views: number;
  linked: number;
  commitId: string;
  created: number;
  updated: number;
  accessed: number;
  snapshotCreated: number;
}

export interface User {
  id: string;
}
